kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-rolebinding
  namespace: myns
subjects:
  - kind: ServiceAccount
    name: example-sa
    namespace: myns
roleRef:
  kind: Role
  name: example-role
  apiGroup: rbac.authorization.k8s.io
