apiVersion: v1
kind: Service
metadata:
  name: kakarot
  labels:
    app: kakarot
  namespace: default
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: web
    port: 5678
    protocol: TCP
    targetPort: 5678
  selector:
    app: kakarot

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  kakarot-deploy
  namespace: default
  labels:
    app:  kakarot
spec:
  selector:
    matchLabels:
      app: kakarot
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  kakarot
    spec:
      containers:
      - name:  kakarot
        args:
        - -text=Hello, Kakarot
        image:  hashicorp/http-echo
      restartPolicy: Always
